### ISSUE TITLE
Reorganizing code

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/dictyconference#2]
1. **Use small components, the render section should not be more than 15-20 lines of code.** Use of smaller and modular components should be done from start, no need to pack everything in one and separate them later on. 
> React is designed around the concept of reusable components. You define small components and you put them together to form bigger components.
2. **Use functional components,** no need to use the class as there is no state and there will be none in the future. Try to follow this logic from the start. 

cc: @sujunglee

**Comment by sujunglee** [comment]
Refactored all the code into functional components
